builds:
-
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm64
  ldflags:
    - -X main.Version={{.Version}}
checksum:
  name_template: 'checksums.txt'
dist: releases
archives:
  - replacements:
    format_overrides:
    - goos: windows
      format: zip
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: pete911
    name: certinfo
brews:
  - tap:
      owner: pete911
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    name: certinfo
    homepage: "https://github.com/pete911/certinfo"
    description: "Print x509 certificate info."
    folder: Formula
    install: |
      bin.install "certinfo"
    test: |
      assert_match /Usage/, shell_output("#{bin}/certinfo -h", 0)
